### ISSUE TITLE
Installed the .deb package on ubuntu but there's no sign of the application anywhere...

### ISSUE THREAD

**Issue by julianorafael** [sachinchoolur/lightgallery-desktop#1]
I don't even know where it installed the files through the .deb package and there's no shortcut to it anywhere. The application should be added to the applications menu.

**Comment by sachinchoolur** [comment]
Hi @julianorafael ,
You can drag lightgallery directly from the Dash into the launcher.

**Comment by tbranyen** [comment]
I installed it as well and cannot seem to find the location of it. I don't have a Dash or launcher since I'm using awesomewm. Was anything placed into my /usr/bin?

**Comment by julianorafael** [comment]
All right, it seems that my ubuntu actually didn't refreshed the app list. After a reboot I managed to find the application.

**Comment by tbranyen** [comment]
I still don't know how to access this program. Where is it installed to?

**Comment by errogaht** [comment]
and me too, don't know how start it
