### ISSUE TITLE
Don't work in windows 10

### ISSUE THREAD

**Issue by PterPmnta** [sachinchoolur/lightgallery-desktop#14]
I try open, but show me that:

[Picture](http://imgur.com/SsmH8nV)

**Comment by sachinchoolur** [comment]
I have tested this on multiple windows 10 machines. 
It works fine. Please re-open if the issue persists..

**Comment by PterPmnta** [comment]
@sachinchoolur Try to open , but still has the same mistake , I'll remove it and reinstall it .

**Comment by PterPmnta** [comment]
@sachinchoolur sorry, but i do it all process again and dont work, i have windows 10 x86

**Comment by smartcorestudio** [comment]
The same issue on Windows 10 x64. There were no errors during the installation process
