### ISSUE TITLE
Typo in lightgallery-desktop/app/stylesheets/main.less

### ISSUE THREAD

**Issue by fraincs** [sachinchoolur/lightgallery-desktop#2]
&.lg-on{
        .lg-drag-drop {
            display: noone;
        }
    }

should be

&.lg-on{
        .lg-drag-drop {
            display: none;
        }
    }

**Comment by sachinchoolur** [comment]
Thank you for pointing this out. I will update it ASAP

**Comment by sachinchoolur** [comment]
Hi,
Sorry for the delay. It is fixed in v0.1.1
