### ISSUE TITLE
Thumbnail resizing squashing the images

### ISSUE THREAD

**Issue by codepo8** [sachinchoolur/lightgallery-desktop#3]
The created thumbnails look pretty squashed, it'd make more sense to fill the canvas around them and keep their original aspect ratio. 

I use the following method for that in [simplethumbnails](https://github.com/codepo8/simplethumbnails):
```javascript
  function resize(imagewidth, imageheight, thumbwidth, thumbheight) {
    var w = 0, h = 0, x = 0, y = 0,
        widthratio  = imagewidth / thumbwidth,
        heightratio = imageheight / thumbheight,
        maxratio    = Math.max( widthratio, heightratio );
    if ( maxratio > 1 ) {
        w = imagewidth / maxratio;
        h = imageheight / maxratio;
    } else {
        w = imagewidth;
        h = imageheight;
    }
    x = ( thumbwidth - w ) / 2;
    y = ( thumbheight - h ) / 2;
    return { w:w, h:h, x:x, y:y };
  }
```
I'm currently on a plane, but I may be able to create a pull request with this soon.

**Comment by sachinchoolur** [comment]
Sorry for the delayed response.
Now i am giving height and width 100% for thumbnails. I think the issue is because of that. I will definitely improve this on next release (Most probably on monday.) 

Thanks ,
Sachin
