### ISSUE TITLE
Animation improvements (Duration and easing)

### ISSUE THREAD

**Issue by ameesme** [sachinchoolur/lightgallery-desktop#4]
Currently, switching between images takes  pretty long with an ease-in-out-like timing. For a better user experience, I think this should probably be shortened, and switched to an ease-out timing, or no animation at all.

This is more similar to Apple's default slideshows.

**Comment by sachinchoolur** [comment]
You can change the duration of the animation and easing from settings.
Menu > views > speed 
Menu > views > Easing 

Any way i will try to adjust it in the next release
