### ISSUE TITLE
Does not open images sent as commandline arguments

### ISSUE THREAD

**Issue by awestroke** [sachinchoolur/lightgallery-desktop#5]
The "open with..." context menu alternative in Windows does open lightGallery, but not with the selected files loaded. So you have to drag and drop to use the program.

I imagine this is true for other platforms as well, from what I can understand of https://github.com/sachinchoolur/lightgallery-desktop/blob/master/app/background.js .

**Comment by sachinchoolur** [comment]
I think electron doesn't support "open with" on windows. But it supports on ubuntu and mac.
